import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation_layout from "./navigation/navigation_layout";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation_layout/>
        {children}
      </body>
    </html>
  );
}
